source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SimplePDF_Example' do
  pod 'SimplePDFSwift', :path => '../'
end

target 'SimplePDF_Tests' do
  pod 'SimplePDFSwift', :path => '../'

  #pod 'Quick', '~> 0.10'
  #pod 'Nimble', '~> 5.1'
end
